# Generated by Django 4.0.5 on 2022-07-01 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_payment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payment',
            old_name='usesr_course',
            new_name='user_course',
        ),
    ]
